=== jeanpmathes/VoxelGame/src/client/Resources/Textures/texture.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="Texture" type="TextureType"/>
    <xs:complexType name="LayerType" mixed="true">
        <xs:sequence>
            <xs:element type="ModifierType" name="Modifier" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="source" use="required"/>
    </xs:complexType>
    <xs:complexType name="ModifierType">
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
    <xs:complexType name="LayersType">
        <xs:sequence>
            <xs:element type="LayerType" name="Layer" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="mode" default="blend"/>
    </xs:complexType>
    <xs:complexType name="ModifiersType">
        <xs:sequence>
            <xs:element type="ModifierType" name="Modifier" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TextureType">
        <xs:sequence>
            <xs:element type="LayersType" name="Layers"/>
            <xs:element type="ModifiersType" name="Modifiers"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jeanpmathes/VoxelGame/src/client/Resources/Textures/Blocks/_test.xml
<Texture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../texture.xsd">
    <Layers mode="overwrite">
        <Layer source="tex#1,2"/>
        <Layer source="p:tex">
            <Modifier type="color" value="#ff0000"/>
            <Modifier type="no-tint"/>
        </Layer>
    </Layers>
    <Modifiers>
        <Modifier type="color" value="#00ff00"/>
        <Modifier type="no-tint"/>
    </Modifiers>
</Texture>

=== jeanpmathes/VoxelGame/src/client/Resources/Textures/Blocks/oak_bed.xml
<Texture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../texture.xsd">
    <Layers mode="replace">
        <Layer source="p:oak:0,0">
            <Modifier type="no-tint"/>
            <Modifier type="repeat" x="2" y="2"/>
        </Layer>
        <Layer source="p:bed_base:all">
            <Modifier type="no-tint"/>
        </Layer>
        <Layer source="p:bed_tinted:all"/>
    </Layers>
    <Modifiers/>
</Texture>
